fix: Refactor eval-overlap script

diff --git a/bin/eval-overlap b/bin/eval-overlap
--- a/bin/eval-overlap
+++ b/bin/eval-overlap
@@ -1,8 +1,16 @@
 #!/bin/bash
 
-appdir="$(cd "$(dirname "$BASH_SOURCE")/.." && pwd)"
-appname="$(basename "$BASH_SOURCE")"
-. "$appdir/lib/daggen/irtk.sh" || { echo "Failed to import daggen/irtk module!" 1>&2; exit 1; }
+appid="$(basename "$0")"
+appdir="$(cd "$(dirname "$BASH_SOURCE")" && pwd)"
+appdir="$(cd "$appdir/.." && pwd)"
+
+source "$appdir/lib/daggen/utils.sh" || {
+  echo "Failed to import daggen/utils module!" 1>&2
+  exit 1
+}
+source "$appdir/etc/config/default.sh" || {
+  error "Failed to load default configuration"
+}
 
 # ==============================================================================
 # help
@@ -13,38 +21,37 @@ print_help()
 {
   cat <<HELP
 
-usage: $(basename "$0") [options]
+usage: $appid [options]
 
 Compute overlap of all pairwise transformations.
 
 Options:
-  -s -sublst <sub.lst>     Text file listing the IDs of the images
-                           to use for the atlas construction. If not
-                           specified, the IDs are read from the -agelst.
-                           (default: $appdir/etc/sub.lst)
-
-  -a -agelst <age.csv>     Comma/space-separated CSV file, where the
-                           first column contains the image ID and the
-                           second column the associated age.
-                           (default: $appdir/etc/age.csv)
-
-  -c -config <config.sh>   Configuration file.
-                           (default: $appdir/etc/config.sh)
-
-  -i -input <dir>          Input directory containing the warped label maps.
-                           (default: $indir)
-
-  -o -output <dir>         Output directory where to write the results to.
-                           (default: $outdir)
-
-  -l -label  <label>...    Segmentation label: 1=CSF, 2=cGM, 3=WM, 4=BG, 5=VENT, 6=Cerebellum+Brainstem, 7=dGM.
-                           (default: all, excl. BG)
-
-  -m -metric <metric>      Overlap metric: Sensitivity, Specificity, Dice, Jaccard.
-                           (default: Dice)
-
-  -h -help                 Print help and exit.
-  -v -verbose              Enable verbose output messages.
+  -c, -config <config.sh>
+      Custom configuration file. (default: none)
+  -a, -agelst <age.csv>
+      Comma/space-separated CSV file, where the first column contains
+      the image ID and the second column the associated age.
+      (default: $agelst)
+  -s, -sublst <sub.lst>
+      Text file listing the IDs of the images to use for the atlas construction.
+      If not specified, the IDs are read from the -agelst.
+      (default: $sublst)
+  -i -input <dir>
+      Input directory containing the warped label maps.
+      (default: $inpdir)
+  -o -output <dir>
+      Output directory where to write the results to.
+      (default: $resdir)
+  -l -label <label>...
+      Segmentation label.
+      (default: Draw-EM tissue labels)
+  -m -metric <metric>
+      Overlap metric: Sensitivity, Specificity, Dice, Jaccard.
+      (default: Dice)
+  -h -help
+      Print help and exit.
+  -v -verbose
+      Enable verbose output messages.
 HELP
 }
 
@@ -68,29 +75,33 @@ label_name()
 # main
 # ==============================================================================
 
-verbose=0
-options=()
-label=(1 2 3 5 6 7)
-metric='Dice'
-sublst=
-agelst="$appdir/etc/age.csv"
-config="$appdir/etc/config.sh"
-indir="$(cd  "$appdir/../eval/warped-labels" && pwd)"
-outdir="$(cd "$appdir/../eval/overlap"       && pwd)"
-
 o=0
 while [ $o -lt $# ]; do
   case "${!o}" in
-    -c|-config) let a=o+1; optarg config ${!o} "${!a}"; ;;
+    -c|-config)
+      let a=o+1; optarg config ${!o} "${!a}";
+      source "$config" || {
+        error "Failed to load configuration from file: $config"
+      }
+      ;;
   esac
   let o++
 done
-. "$config"  || error "Failed to load configuration from file: $config"
+
+[ -z "$agelst" ] || agelst="$topdir/$agelst"
+[ -z "$sublst" ] || sublst="$topdir/$sublst"
+
+options=()
+label=(1 2 3 5 6 7 8 9)
+metric='Dice'
+evldir="$(cd "$topdir/.." && pwd)/eval"
+inpdir="$evldir/warped-tissues"
+resdir="$evldir/overlap"
 
 while [ $# -gt 0 ]; do
   case "$1" in
-    -i|-input)       optarg indir  $1 "$2"; shift; ;;
-    -o|-output)      optarg outdir $1 "$2"; shift; ;;
+    -i|-input)       optarg inpdir $1 "$2"; shift; ;;
+    -o|-output)      optarg resdir $1 "$2"; shift; ;;
     -s|-sublst)      optarg sublst $1 "$2"; shift; ;;
     -a|-agelst)      optarg agelst $1 "$2"; shift; ;;
     -c|-config)      shift; ;; # already loaded
@@ -103,13 +114,10 @@ while [ $# -gt 0 ]; do
   shift
 done
 
-if [ -z "$agelst" ]; then
+if [ -z "$agelst" ] || [ ! -f "$agelst" ]; then
   error "Missing CSV file with subject IDs and corresponding ages!"
 fi
-if [ -z "$sublst" ]; then
-  sublst="$appdir/etc/sub.lst"
-  [ -f "$sublst" ] || sublst="$agelst"
-fi
+[ -n "$sublst" ] || sublst="$agelst"
 read_sublst subids "$sublst"
 
 csv_header=''
@@ -118,26 +126,28 @@ for id2 in ${subids[@]}; do
   csv_header="$csv_header$id2"
 done
 
-mkdir -p "$outdir" || exit 1
+mkdir -p "$resdir" || error "Failed to create output directory"
 
 for lbl in ${label[@]}; do
-  structure=$(label_name $lbl)
+  #structure=$(label_name $lbl)
+  structure="label_$lbl"
   [ $verbose -le 0 ] || echo "Evaluating pairwise overlap for $structure..."
-  csv_name="$outdir/$metric-${structure}.csv"
-  rm -f "${csv_name}"
-  echo "${csv_header}" >> "${csv_name}"
+  csv_name="$resdir/${metric}_of_${structure}.csv"
+  rm -f "$csv_name"
+  echo "$csv_header" >> "$csv_name"
   t=0
   for id1 in ${subids[@]}; do
     let t++
-    [ $verbose -le 1 ] || echo "Evaluating pairwise overlap for $structure... $(printf %3d/%d $t ${#subids[@]}) (target=$id1)"
-    tgt="$indir/$id1/$id1-tissues.nii.gz"
+    [ $verbose -le 1 ] || {
+      echo "Evaluating pairwise overlap for $structure... $(printf %3d/%d $t ${#subids[@]}) (target=$id1)"
+    }
+    tgt="$inpdir/$id1/$id1.nii.gz"
     src=()
     for id2 in ${subids[@]}; do
-      src=("${src[@]}" "$indir/$id1/$id2-tissues.nii.gz")
+      src=("${src[@]}" "$inpdir/$id1/$id2.nii.gz")
     done
-    overlap "$tgt" "${src[@]}" -v 0 -metric $metric -label $lbl -delim ',' >> "${csv_name}"
+    mirtk evaluate-overlap "$tgt" "${src[@]}" -v 0 -metric $metric -label $lbl -delim ',' >> "${csv_name}"
     echo >> "${csv_name}"
   done
   [ $verbose -le 0 ] || echo "Evaluating pairwise overlap for $structure... done"
 done
-wait
