Write generated kernel files to subdirectory. Add script to determine unique image pairs to register.

diff --git a/bin/kernel b/bin/kernel
--- a/bin/kernel
+++ b/bin/kernel
@@ -1,7 +1,8 @@
 #! /bin/bash
 
-appdir="$(cd $(dirname "$BASH_SOURCE") && pwd)"
+appdir="$(cd "$(dirname "$BASH_SOURCE")/.." && pwd)"
 appname="$(basename "$BASH_SOURCE")"
+. "$appdir/lib/daggen/irtk.sh" || { echo "Failed to import daggen/irtk module!" 1>&2; exit 1; }
 
 # ==============================================================================
 # help
@@ -22,12 +23,12 @@ Options:
   -s -sublst <sub.lst>     Text file listing the IDs of the images
                            to use for the atlas construction. If not
                            specified, the IDs are read from the -agelst.
-                           (default: $appdir/sub.lst)
+                           (default: $appdir/etc/sub.lst)
 
   -a -agelst <age.csv>     Comma/space-separated CSV file, where the
                            first column contains the image ID and the
                            second column the associated age.
-                           (default: $appdir/age.csv)
+                           (default: $appdir/etc/age.csv)
 
   -c -config <config.sh>   Configuration file.
                            (default: $appdir/etc/config.sh)
@@ -52,71 +53,6 @@ Options:
   -h -help                 Print help and exit.
   -v -verbose              Enable verbose output messages.
 HELP
-}
-
-# ==============================================================================
-# used lib/daggen/core.sh functions
-# ==============================================================================
-
-[ -n "$verbose" ] || verbose=0 # global verbosity level
-
-# ------------------------------------------------------------------------------
-# print message
-info()  { [ $verbose -lt 1 ] || echo -e "$1"; }
-warn()  { echo -e "$1" 1>&2; }
-error() { warn "$1"; exit 1; }
-
-# ------------------------------------------------------------------------------
-# usage: foo () { local "$1" && upvar $1 "Hello, World!" }
-upvar()
-{
-  if unset -v "$1"; then       # unset & validate varname
-    if (( $# == 2 )); then
-      eval $1=\"\$2\"          # return single value
-    else
-      eval $1=\(\"\${@:2}\"\)  # return array
-    fi
-  fi
-}
-
-# ------------------------------------------------------------------------------
-# get command-line option argument
-optarg()
-{
-  [ -n "$3" ] || { echo "Option $2 requires an argument!" 1>&2; exit 1; }
-  local "$1" && upvar $1 "$3"
-}
-
-# ------------------------------------------------------------------------------
-# get command-line option arguments
-optargs()
-{
-  local var="$1"
-  local opt="$2"
-  local arg=()
-  shift 2
-  while [ $# -gt 0 ]; do
-    case "$1" in
-      -*) break; ;;
-      *)  arg=("${arg[@]}" "$1"); ;;
-    esac
-    shift
-  done
-  [ ${#arg[@]} -gt 0 ] || { echo "Option $opt requires an argument!" 1>&2; exit 1; }
-  local "$var" && upvar $var "${arg[@]}"
-}
-
-# ==============================================================================
-# used lib/daggen/irtk.sh functions
-# ==============================================================================
-
-# ------------------------------------------------------------------------------
-# read subject IDs from text file (first column)
-read_sublst()
-{
-  local ids=($(cat "$2" | cut -d' ' -f1 | cut -d, -f1 | cut -d# -f1))
-  [ ${#ids[@]} -gt 0 ] || error "Failed to read subject IDs from file $2"
-  local "$1" && upvar $1 ${ids[@]}
 }
 
 # ==============================================================================
@@ -222,12 +158,15 @@ generate_kernel()
     error "generate_kernel: either -num or -dt option required when using a -range"
   fi
 
+  # create directory for kernel files
+  makedir "$kernel"
+
   # compute kernel weight for each subject
   info "Generating ${#kernel_mean[@]} kernel list(s)..."
   k=0
   for mu in ${kernel_mean[@]}; do
     std=${kernel_sigma[$k]}
-    lst="kernel_t=$mu.lst"
+    lst="$kernel/weights_t=$mu.csv"
     i=0
     for id in ${ids[@]}; do
       w=$(gaussian ${age[$i]} $mu $std)
@@ -248,11 +187,11 @@ generate_kernel()
 
 verbose=0
 epsilon=0.001
-sigma=2
-kernel=()
+sigma=1
+options=()
 sublst=
-agelst="$appdir/age.csv"
-config="$appdir/config.sh"
+agelst="$appdir/etc/age.csv"
+config="$appdir/etc/config.sh"
 
 o=0
 while [ $o -lt $# ]; do
@@ -270,7 +209,7 @@ while [ $# -gt 0 ]; do
     -c|-config)      shift; ;; # already loaded
     -h|-help|--help) print_help; exit 0; ;;
     -v|-verbose)     let verbose++; ;;
-    *)               kernel=("${kernel[@]}" "$1"); ;;
+    *)               options=("${options[@]}" "$1"); ;;
   esac
   shift
 done
@@ -279,7 +218,7 @@ if [ -z "$agelst" ]; then
   error "Missing CSV file with subject IDs and corresponding ages!"
 fi
 if [ -z "$sublst" ]; then
-  sublst="$appdir/sub.lst"
+  sublst="$appdir/etc/sub.lst"
   [ -f "$sublst" ] || sublst="$agelst"
 fi
 read_sublst subids "$sublst"
@@ -294,8 +233,10 @@ for id in ${subids[@]}; do
   let i++
 done
 
+cd "$topdir" || error "Failed to change to top-level directory!"
+
 generate_kernel -subjects "${subids[@]}" \
                 -ages     "${subage[@]}" \
                 -epsilon  $epsilon       \
                 -sigma    $sigma         \
-                "${kernel[@]}"
+                "${options[@]}"
