Change workflow layout.

diff --git a/bin/make_atlas_builder b/bin/make_atlas_builder
--- a/bin/make_atlas_builder
+++ b/bin/make_atlas_builder
@@ -22,15 +22,15 @@ Options:
   -s -sublst <sub.lst>     Text file listing the IDs of the images
                            to use for the atlas construction. If not
                            specified, the IDs are read from the -agelst.
-                           (default: $pardir/(|0_|0___|0.0_)sub.lst)
+                           (default: $appdir/etc/sub.lst)
 
   -a -agelst <age.csv>     Comma/space-separated CSV file, where the
                            first column contains the image ID and the
                            second column the associated age.
-                           (default: $pardir/(|0_|0___|0.0_)age.csv)
+                           (default: $appdir/etc/age.csv)
 
   -c -config <config.sh>   Configuration file.
-                           (default: (<cwd>|$appdir)/etc/config.sh)
+                           (default: $appdir/etc/config.sh)
 
   -h -help                 Print help and exit.
   -v -verbose              Enable verbose output messages.
@@ -41,8 +41,11 @@ HELP
 # configuration
 # ==============================================================================
 
-config="$PWD/etc/config.sh"
-[ -f "$config" ] || config="$appdir/etc/config.sh"
+verbose=0
+sublst=
+agelst="$appdir/etc/age.csv"
+config="$appdir/etc/config.sh"
+
 o=0
 while [ $o -lt $# ]; do
   case "${!o}" in
@@ -51,15 +54,6 @@ while [ $o -lt $# ]; do
   let o++
 done
 . "$config"  || error "Failed to load configuration from file: $config"
-cd "$topdir" || error "Failed to change to top-level directory!"
-
-# ==============================================================================
-# initialization
-# ==============================================================================
-
-verbose=0
-sublst=
-agelst=
 
 while [ $# -gt 0 ]; do
   case "$1" in
@@ -77,38 +71,19 @@ while [ $# -gt 0 ]; do
   shift
 done
 
-if [ -z "$sublst" ]; then
-  for name in 0___sub 0.0_sub 0_sub sub; do
-    info "Looking for $topdir/$pardir/$name.lst..."
-    if [ -f "$topdir/$pardir/$name.lst" ]; then
-      [ -z "$sublst" ] || error "Multiple subject lists found in $topdir/$pardir!"
-      sublst="$topdir/$pardir/$name.lst"
-      info "Looking for $topdir/$pardir/$name.lst... found"
-    else
-      info "Looking for $topdir/$pardir/$name.lst... not found"
-    fi
-  done
-fi
 if [ -z "$agelst" ]; then
-  for name in 0___age 0.0_age 0_age age; do
-    info "Looking for $topdir/$pardir/$name.csv..."
-    if [ -f "$topdir/$pardir/$name.csv" ]; then
-      [ -z "$agelst" ] || error "Multiple age lists found in $topdir/$pardir!"
-      agelst="$topdir/$pardir/$name.csv"
-      info "Looking for $topdir/$pardir/$name.csv... found"
-    else
-      info "Looking for $topdir/$pardir/$name.csv... not found"
-    fi
-  done
+  error "Missing CSV file with subject IDs and corresponding ages!"
 fi
-
-[ -n "$agelst" ] || error "Missing CSV file with subject IDs and corresponding ages!"
-[ -n "$sublst" ] || sublst="$agelst"
+if [ -z "$sublst" ]; then
+  sublst="$appdir/etc/sub.lst"
+  [ -f "$sublst" ] || sublst="$agelst"
+fi
 read_sublst subids "$sublst"
 
-makedir "$bindir"
-makedir "$libdir"
-makedir "$pardir"
+cd "$topdir" || error "Failed to change to top-level directory!"
+
+makedir "$moddir"
+makedir "$dagdir"
 
 # ==============================================================================
 section='# 1. linear normalization'
@@ -176,23 +151,23 @@ make_dofcombine_node \
     -logdir   "$logdir/1.6_finalize_dofs"
 
 # ------------------------------------------------------------------------------
-# subworkflow
-dagfile="$bindir/1_normalization.dag"
+# DAG file
+dagfile="$dagdir/1_normalization.dag"
 cat --<<EOF > "$dagfile"
 $section
-JOB        1_init     $topdir/$libdir/1.1_initialize_dofs.job
-JOB        1_affreg1  $topdir/$libdir/1.2_affine_registration.job
-JOB        1_avgdof1  $topdir/$libdir/1.3_average_dofs.job
-JOB        1_affreg2  $topdir/$libdir/1.4_affine_refinement.job
-JOB        1_avgdof2  $topdir/$libdir/1.5_average_dofs.job
-JOB        1_final    $topdir/$libdir/1.6_finalize_dofs.job
+JOB        1_init     $topdir/$moddir/1.1_initialize_dofs.job
+JOB        1_affreg1  $topdir/$moddir/1.2_affine_registration.job
+JOB        1_avgdof1  $topdir/$moddir/1.3_average_dofs.job
+JOB        1_affreg2  $topdir/$moddir/1.4_affine_refinement.job
+JOB        1_avgdof2  $topdir/$moddir/1.5_average_dofs.job
+JOB        1_final    $topdir/$moddir/1.6_finalize_dofs.job
 
-SCRIPT PRE 1_init     $topdir/$libdir/1.1_initialize_dofs.pre
-SCRIPT PRE 1_affreg1  $topdir/$libdir/1.2_affine_registration.pre
-SCRIPT PRE 1_avgdof1  $topdir/$libdir/1.3_average_dofs.pre
-SCRIPT PRE 1_affreg2  $topdir/$libdir/1.4_affine_refinement.pre
-SCRIPT PRE 1_avgdof2  $topdir/$libdir/1.5_average_dofs.pre
-SCRIPT PRE 1_final    $topdir/$libdir/1.6_finalize_dofs.pre
+SCRIPT PRE 1_init     $topdir/$moddir/1.1_initialize_dofs.pre
+SCRIPT PRE 1_affreg1  $topdir/$moddir/1.2_affine_registration.pre
+SCRIPT PRE 1_avgdof1  $topdir/$moddir/1.3_average_dofs.pre
+SCRIPT PRE 1_affreg2  $topdir/$moddir/1.4_affine_refinement.pre
+SCRIPT PRE 1_avgdof2  $topdir/$moddir/1.5_average_dofs.pre
+SCRIPT PRE 1_final    $topdir/$moddir/1.6_finalize_dofs.pre
 
 PARENT 1_init    CHILD 1_affreg1
 PARENT 1_affreg1 CHILD 1_avgdof1
@@ -207,7 +182,8 @@ section='# 2. spatio-temporal deformation'
 # ==============================================================================
 
 # ------------------------------------------------------------------------------
-dagfile="$bindir/2_deformation.dag"
+# DAG file
+dagfile="$dagdir/2_deformation.dag"
 cat --<<EOF > "$dagfile"
 $section
 EOF
@@ -218,8 +194,8 @@ section='# 3. anatomical template creation'
 # ==============================================================================
 
 # ------------------------------------------------------------------------------
-# subworkflow
-dagfile="$bindir/3_anatomy.dag"
+# DAG file
+dagfile="$dagdir/3_anatomy.dag"
 cat --<<EOF > "$dagfile"
 $section
 EOF
@@ -230,8 +206,8 @@ section='# 4. tissue probability maps'
 # ==============================================================================
 
 # ------------------------------------------------------------------------------
-# subworkflow
-dagfile="$bindir/4_tissues.dag"
+# DAG file
+dagfile="$dagdir/4_tissues.dag"
 cat --<<EOF > "$dagfile"
 $section
 EOF
@@ -242,8 +218,8 @@ section='# 5. structure probability maps'
 # ==============================================================================
 
 # ------------------------------------------------------------------------------
-# subworkflow
-dagfile="$bindir/5_structures.dag"
+# DAG file
+dagfile="$dagdir/5_structures.dag"
 cat --<<EOF > "$dagfile"
 $section
 EOF
@@ -253,28 +229,20 @@ EOF
 # DAGMan application
 # ==============================================================================
 
-dagfile="$bindir/0_make_atlas.dag"
-
-cat --<<EOF                          >  "$dagfile"
+dagfile="$dagdir/0_make_atlas.dag"
+cat --<<EOF >  "$dagfile"
 # HTCondor DAGMan application for the consistent construction of a
 # spatio-temporal brain atlas and growth model from cross-sectional
 # brain MR images and automatic tissue and structure segmentations
 
-EOF
-cat "$bindir/1_normalization.dag"    >> "$dagfile"
-echo                                 >> "$dagfile"
-cat "$bindir/2_deformation.dag"      >> "$dagfile"
-echo                                 >> "$dagfile"
-cat "$bindir/3_anatomy.dag"          >> "$dagfile"
-echo                                 >> "$dagfile"
-cat "$bindir/4_tissues.dag"          >> "$dagfile"
-echo                                 >> "$dagfile"
-cat "$bindir/5_structures.dag"       >> "$dagfile"
-cat --<<EOF                          >> "$dagfile"
+SUBDAG EXTERNAL proc1 $topdir/$dagdir/1_normalization.dag
+SUBDAG EXTERNAL proc2 $topdir/$dagdir/2_deformation.dag
+SUBDAG EXTERNAL proc3 $topdir/$dagdir/3_anatomy.dag
+SUBDAG EXTERNAL proc4 $topdir/$dagdir/4_tissues.dag
+SUBDAG EXTERNAL proc5 $topdir/$dagdir/5_structures.dag
 
-# inter-workflow dependencies
-PARENT 1_final CHILD 2_init
-PARENT 2_final CHILD 3_init
-PARENT 3_final CHILD 4_init
-PARENT 4_final CHILD 5_init
+PARENT proc1 CHILD proc2
+PARENT proc2 CHILD proc3
+PARENT proc3 CHILD proc4
+PARENT proc4 CHILD proc5
 EOF
