fix: Make log directory if not existent

diff --git a/lib/tools/submit-dag-to-condor b/lib/tools/submit-dag-to-condor
--- a/lib/tools/submit-dag-to-condor
+++ b/lib/tools/submit-dag-to-condor
@@ -51,6 +51,7 @@ if [ $log = '/' ]; then
   echo "Critical log argument, rm -rf would be fatal!" 1>&2
   exit 1
 fi
+mkdir -p "$(dirname "$log")" || error "Failed to make directory of log file."
 
 # required commands
 dagman="$(which condor_dagman)"
